# constants.py
DEFAULT_UPPER_LIMIT = 10000

# Differential evolution constants
DE_BASE_INDEX_STRATEGY_RAND = "rand"
DE_BASE_INDEX_STRATEGY_BETTER = "better"
DE_BASE_INDEX_STRATEGY_TARGET_TO_BEST = "target-to-best"
DE_BASE_INDEX_STRATEGY_BEST = "best"
DE_BASE_INDEX_STRATEGY_TARGET_TO_BEST_K_VALUE = 0.5

DE_DIFFERENTIAL_WEIGHTS_STRATEGY_GIVEN = "given"
DE_DIFFERENTIAL_WEIGHTS_STRATEGY_DITHER = "dither"
DE_DIFFERENTIAL_WEIGHTS_STRATEGY_JITTER = "jitter"
DE_RECOMBINATION_STRATEGY_BINOMIAL = "binomial"
DE_RECOMBINATION_STRATEGY_EXPONENTIAL = "exponential"


# Evolutionary strategy constants
ES_RECOMBINATION_STRATEGY_DISCRETE = "discrete"
ES_RECOMBINATION_STRATEGY_AVERAGE_INTERMEDIATE = "averaged_intermediate"
ES_RECOMBINATION_STRATEGY_GENERALIZED_INTERMEDIATE = "generalized_intermediate"
ES_RECOMBINATION_STRATEGY_INTERMEDIATE_AVERAGED = "averaged"
ES_SURVIVOR_STRATEGY_MU_LAMBDA = "mu, lambda"
ES_SURVIVOR_STRATEGY_MU_PLUS_LAMBDA = "mu+lambda"

OPTIMIZER_EVOLUTIONARY_STRATEGIES = "evolutionary_strategies"
OPTIMIZER_DIFFERENTIAL_EVOLUTION = "differential_evolution"

DISCOUNT_FACTOR = 0.99
MAX_GENERATIONS = 1000
